### ISSUE TITLE
IllegalArgumentException on server start-up

### ISSUE THREAD

**Issue by SlimeDog** [Ugleh/RedstoneProximitySensor#16]
Paper 1.21.1-83
RedstoneProximitySensor 2.5.2

Paper changes some internals. On server start-up:
```
[22:23:52] [Server thread/INFO]: [RedstoneProximitySensor] Enabling RedstoneProximitySensor v2.5.2
[22:23:53] [Server thread/ERROR]: Error occurred while enabling RedstoneProximitySensor v2.5.2 (Is it up to date?)
java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228) ~[?:?]
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115) ~[?:?]
        at java.base/java.lang.reflect.Field.set(Field.java:836) ~[?:?]
        at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.util.SkullCreator.mutateItemMeta(SkullCreator.java:298) ~[RedstoneProximitySensor-2.5.2.jar:?]
        at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.util.SkullCreator.itemWithBase64(SkullCreator.java:161) ~[RedstoneProximitySensor-2.5.2.jar:?]
        at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.util.SkullCreator.itemFromBase64(SkullCreator.java:91) ~[RedstoneProximitySensor-2.5.2.jar:?]
        at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.trigger.IndividualMob.createMainMenu(IndividualMob.java:120) ~[RedstoneProximitySensor-2.5.2.jar:?]
        at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.trigger.IndividualMob.<init>(IndividualMob.java:47) ~[RedstoneProximitySensor-2.5.2.jar:?]
        at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.listener.PlayerListener.createMenu(PlayerListener.java:100) ~[RedstoneProximitySensor-2.5.2.jar:?]
        at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.listener.PlayerListener.<init>(PlayerListener.java:49) ~[RedstoneProximitySensor-2.5.2.jar:?]
        at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.RedstoneProximitySensor.onEnable(RedstoneProximitySensor.java:70) ~[RedstoneProximitySensor-2.5.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-82-1348e44] 
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
[22:23:53] [Server thread/INFO]: [RedstoneProximitySensor] Disabling RedstoneProximitySensor v2.5.2
[22:23:53] [Server thread/ERROR]: Error occurred while disabling RedstoneProximitySensor v2.5.2
java.lang.NullPointerException: Cannot read field "userSelectedInventory" because "this.playerListener" is null
        at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.RedstoneProximitySensor.onDisable(RedstoneProximitySensor.java:132) ~[RedstoneProximitySensor-2.5.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
```

**Comment by SlimeDog** [comment]
Dev hasn't been active for over 3 years, so RedstoneProximitySensor is dead, unless Paper reverts the change or someone forks and updates.

**Comment by CloudeLecaw** [comment]
currently you only can change back to paper 77
they changed how paper handles custom heads and because the GUI has 2 custom heads...

![23-09-2024_00-38-51](https://github.com/user-attachments/assets/41563466-c155-4fcf-8f90-1ec3b57fce6f)

So you have

Opion 1.  - find a Developer that updates it..

Option 2. - Went back to paper 1.21.1 Build 77

**Comment by CloudeLecaw** [comment]
> Paper 1.21.1-83 RedstoneProximitySensor 2.5.2
> 
> Paper changes some internals. On server start-up:
> 
> ```
> [22:23:52] [Server thread/INFO]: [RedstoneProximitySensor] Enabling RedstoneProximitySensor v2.5.2
> [22:23:53] [Server thread/ERROR]: Error occurred while enabling RedstoneProximitySensor v2.5.2 (Is it up to date?)
> java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
>         at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228) ~[?:?]
>         at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232) ~[?:?]
>         at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115) ~[?:?]
>         at java.base/java.lang.reflect.Field.set(Field.java:836) ~[?:?]
>         at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.util.SkullCreator.mutateItemMeta(SkullCreator.java:298) ~[RedstoneProximitySensor-2.5.2.jar:?]
>         at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.util.SkullCreator.itemWithBase64(SkullCreator.java:161) ~[RedstoneProximitySensor-2.5.2.jar:?]
>         at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.util.SkullCreator.itemFromBase64(SkullCreator.java:91) ~[RedstoneProximitySensor-2.5.2.jar:?]
>         at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.trigger.IndividualMob.createMainMenu(IndividualMob.java:120) ~[RedstoneProximitySensor-2.5.2.jar:?]
>         at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.trigger.IndividualMob.<init>(IndividualMob.java:47) ~[RedstoneProximitySensor-2.5.2.jar:?]
>         at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.listener.PlayerListener.createMenu(PlayerListener.java:100) ~[RedstoneProximitySensor-2.5.2.jar:?]
>         at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.listener.PlayerListener.<init>(PlayerListener.java:49) ~[RedstoneProximitySensor-2.5.2.jar:?]
>         at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.RedstoneProximitySensor.onEnable(RedstoneProximitySensor.java:70) ~[RedstoneProximitySensor-2.5.2.jar:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
>         at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
>         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-82-1348e44] 
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
>         at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
>         at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
>         at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
>         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
>         at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
> [22:23:53] [Server thread/INFO]: [RedstoneProximitySensor] Disabling RedstoneProximitySensor v2.5.2
> [22:23:53] [Server thread/ERROR]: Error occurred while disabling RedstoneProximitySensor v2.5.2
> java.lang.NullPointerException: Cannot read field "userSelectedInventory" because "this.playerListener" is null
>         at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.RedstoneProximitySensor.onDisable(RedstoneProximitySensor.java:132) ~[RedstoneProximitySensor-2.5.2.jar:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
>         at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
>         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
>         at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
>         at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
>         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
>         at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
>         at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
>         at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
>         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
>         at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
> ```

You see even Paper 1.21.1 Build96 doesnt help. So move back to Build77 or may find some good soul that wanne update it aggain :3

```
[23:59:11] [Server thread/INFO]: [RedstoneProximitySensor] Enabling RedstoneProximitySensor v2.5.2
[23:59:11] [Server thread/ERROR]: Error occurred while enabling RedstoneProximitySensor v2.5.2 (Is it up to date?)
java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
	at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228) ~[?:?]
	at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232) ~[?:?]
	at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115) ~[?:?]
	at java.base/java.lang.reflect.Field.set(Field.java:836) ~[?:?]
	at RedstoneProximitySensor_2.5.2.jar/com.ugleh.redstoneproximitysensor.util.SkullCreator.mutateItemMeta(SkullCreator.java:298) ~[RedstoneProximitySensor_2.5.2.jar:?]
	at RedstoneProximitySensor_2.5.2.jar/com.ugleh.redstoneproximitysensor.util.SkullCreator.itemWithBase64(SkullCreator.java:161) ~[RedstoneProximitySensor_2.5.2.jar:?]
	at RedstoneProximitySensor_2.5.2.jar/com.ugleh.redstoneproximitysensor.util.SkullCreator.itemFromBase64(SkullCreator.java:91) ~[RedstoneProximitySensor_2.5.2.jar:?]
	at RedstoneProximitySensor_2.5.2.jar/com.ugleh.redstoneproximitysensor.trigger.IndividualMob.createMainMenu(IndividualMob.java:120) ~[RedstoneProximitySensor_2.5.2.jar:?]
	at RedstoneProximitySensor_2.5.2.jar/com.ugleh.redstoneproximitysensor.trigger.IndividualMob.<init>(IndividualMob.java:47) ~[RedstoneProximitySensor_2.5.2.jar:?]
	at RedstoneProximitySensor_2.5.2.jar/com.ugleh.redstoneproximitysensor.listener.PlayerListener.createMenu(PlayerListener.java:100) ~[RedstoneProximitySensor_2.5.2.jar:?]
	at RedstoneProximitySensor_2.5.2.jar/com.ugleh.redstoneproximitysensor.listener.PlayerListener.<init>(PlayerListener.java:49) ~[RedstoneProximitySensor_2.5.2.jar:?]
	at RedstoneProximitySensor_2.5.2.jar/com.ugleh.redstoneproximitysensor.RedstoneProximitySensor.onEnable(RedstoneProximitySensor.java:70) ~[RedstoneProximitySensor_2.5.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[23:59:11] [Server thread/INFO]: [RedstoneProximitySensor] Disabling RedstoneProximitySensor v2.5.2
[23:59:11] [Server thread/ERROR]: Error occurred while disabling RedstoneProximitySensor v2.5.2
java.lang.NullPointerException: Cannot read field "userSelectedInventory" because "this.playerListener" is null
	at RedstoneProximitySensor_2.5.2.jar/com.ugleh.redstoneproximitysensor.RedstoneProximitySensor.onDisable(RedstoneProximitySensor.java:132) ~[RedstoneProximitySensor_2.5.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by SlimeDog** [comment]
Realistically, going backwards is not a viable option. I was hoping to goad some developer into forking and updating. I used to do this sort of thing if I cared about a plugin, but I'm retired (and no longer run Minecraft servers), so it won't be me.

**Comment by CloudeLecaw** [comment]
> Dev hasn't been active for over 3 years, so RedstoneProximitySensor is dead, unless Paper reverts the change or someone forks and updates.

i agree

by the way.. we are using your AggressiveAnimals Forks on our 1.21.1 Server :D

**Comment by CloudeLecaw** [comment]
![Screenshot_2024-09-23-12-43-37-118_com discord-edit](https://github.com/user-attachments/assets/449bbaf2-b49c-4413-aa36-3e9cc0c90284)

This is what a dev of an other plugin wrote me.
looks like he found out what needs to be done.

but now we need to find a dev that can manage the this cideside for this plugin :D

**Comment by SlimeDog** [comment]
> but now we need to find a dev that can manage the this cideside for this plugin :D

Good luck.

**Comment by CloudeLecaw** [comment]
i can agree the version you uploaded there works with latest paper 1.21.1 build 98 =)
Thank you for sharing this update with us <3

https://github.com/Ugleh/RedstoneProximitySensor/pull/18

**Comment by Ugleh** [comment]
I hate to say it but I won't be around to be making updates to these plugins anymore. I am glad @mastercake10 came in and helped out. You might want to consider looking at a different way to do what you need to do like skulk sensors.

I appreciate you all using it, and especially you @SlimeDog for being there with me every step of the way.

**Comment by SlimeDog** [comment]
> I appreciate you all using it, and especially you @SlimeDog for being there with me every step of the way.

It's been a pleasure working with you and other devs, every step of the way. But I no longer run MC servers, and my own plugins are now EOL as well.

**Comment by the-w41k3r** [comment]
> I hate to say it but I won't be around to be making updates to these plugins anymore. I am glad @mastercake10 came in and helped out. You might want to consider looking at a different way to do what you need to do like skulk sensors.
> 
> I appreciate you all using it, and especially you @SlimeDog for being there with me every step of the way.

Would you be willing to pass on this resource to me? I would love to continue developing and maintaining this plugin.
