### ISSUE TITLE
New Paper Versions dont like the plugin

### ISSUE THREAD

**Issue by CloudeLecaw** [Ugleh/RedstoneProximitySensor#17]
paper made changed with 1.21.1 build 78+  so if we dont wanne stay at this version might be able to write a little fix?
We are on build96 and it doesnt look like paper wanne fix this :/

```
[23:59:11] [Server thread/INFO]: [RedstoneProximitySensor] Enabling RedstoneProximitySensor v2.5.2
[23:59:11] [Server thread/ERROR]: Error occurred while enabling RedstoneProximitySensor v2.5.2 (Is it up to date?)
java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
	at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228) ~[?:?]
	at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232) ~[?:?]
	at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115) ~[?:?]
	at java.base/java.lang.reflect.Field.set(Field.java:836) ~[?:?]
	at RedstoneProximitySensor_2.5.2.jar/com.ugleh.redstoneproximitysensor.util.SkullCreator.mutateItemMeta(SkullCreator.java:298) ~[RedstoneProximitySensor_2.5.2.jar:?]
	at RedstoneProximitySensor_2.5.2.jar/com.ugleh.redstoneproximitysensor.util.SkullCreator.itemWithBase64(SkullCreator.java:161) ~[RedstoneProximitySensor_2.5.2.jar:?]
	at RedstoneProximitySensor_2.5.2.jar/com.ugleh.redstoneproximitysensor.util.SkullCreator.itemFromBase64(SkullCreator.java:91) ~[RedstoneProximitySensor_2.5.2.jar:?]
	at RedstoneProximitySensor_2.5.2.jar/com.ugleh.redstoneproximitysensor.trigger.IndividualMob.createMainMenu(IndividualMob.java:120) ~[RedstoneProximitySensor_2.5.2.jar:?]
	at RedstoneProximitySensor_2.5.2.jar/com.ugleh.redstoneproximitysensor.trigger.IndividualMob.<init>(IndividualMob.java:47) ~[RedstoneProximitySensor_2.5.2.jar:?]
	at RedstoneProximitySensor_2.5.2.jar/com.ugleh.redstoneproximitysensor.listener.PlayerListener.createMenu(PlayerListener.java:100) ~[RedstoneProximitySensor_2.5.2.jar:?]
	at RedstoneProximitySensor_2.5.2.jar/com.ugleh.redstoneproximitysensor.listener.PlayerListener.<init>(PlayerListener.java:49) ~[RedstoneProximitySensor_2.5.2.jar:?]
	at RedstoneProximitySensor_2.5.2.jar/com.ugleh.redstoneproximitysensor.RedstoneProximitySensor.onEnable(RedstoneProximitySensor.java:70) ~[RedstoneProximitySensor_2.5.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[23:59:11] [Server thread/INFO]: [RedstoneProximitySensor] Disabling RedstoneProximitySensor v2.5.2
[23:59:11] [Server thread/ERROR]: Error occurred while disabling RedstoneProximitySensor v2.5.2
java.lang.NullPointerException: Cannot read field "userSelectedInventory" because "this.playerListener" is null
	at RedstoneProximitySensor_2.5.2.jar/com.ugleh.redstoneproximitysensor.RedstoneProximitySensor.onDisable(RedstoneProximitySensor.java:132) ~[RedstoneProximitySensor_2.5.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by CloudeLecaw** [comment]
closed because its allready reported
