### ISSUE TITLE
Incompatibility with Spigot latest

### ISSUE THREAD

**Issue by SlimeDog** [Ugleh/RedstoneProximitySensor#4]
Spigot 1.12.2 latest
RedstoneProximitySensor 2.3.7

No issues with Spigot releases prior to 2018-06-27.

```
[06:15:13] [Server thread/ERROR]: Error occurred while enabling RedstoneProximitySensor v2.3.7 (Is it up to date?)
java.lang.IllegalArgumentException: key
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[spigot-1.12.2.jar-2018-07-10-0613:git-Spigot-642f6d2-ab13683]
        at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:72) ~[spigot-1.12.2.jar-2018-07-10-0613:git-Spigot-642f6d2-ab13683]
        at com.ugleh.redstoneproximitysensor.RedstoneProximitySensor.createRecipes(RedstoneProximitySensor.java:116) ~[?:?]
        at com.ugleh.redstoneproximitysensor.RedstoneProximitySensor.onEnable(RedstoneProximitySensor.java:80) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar-2018-07-10-0613:git-Spigot-642f6d2-ab13683]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar-2018-07-10-0613:git-Spigot-642f6d2-ab13683]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar-2018-07-10-0613:git-Spigot-642f6d2-ab13683]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar-2018-07-10-0613:git-Spigot-642f6d2-ab13683]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar-2018-07-10-0613:git-Spigot-642f6d2-ab13683]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar-2018-07-10-0613:git-Spigot-642f6d2-ab13683]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar-2018-07-10-0613:git-Spigot-642f6d2-ab13683]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar-2018-07-10-0613:git-Spigot-642f6d2-ab13683]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar-2018-07-10-0613:git-Spigot-642f6d2-ab13683]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar-2018-07-10-0613:git-Spigot-642f6d2-ab13683]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by SlimeDog** [comment]
Hmmm. Must have been a Spigot issue. No issue with latest build.
