### ISSUE TITLE
Spigot 1.13 update required

### ISSUE THREAD

**Issue by SlimeDog** [Ugleh/RedstoneProximitySensor#5]
Spigot 1.13 latest
RPS 2.3.7

```
[14:10:38] [Server thread/INFO]: [RedstoneProximitySensor] Enabling RedstoneProximitySensor v2.3.7
[14:10:38] [Server thread/ERROR]: Error occurred while enabling RedstoneProximitySensor v2.3.7 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.enchantments.Enchantment.<init>(I)V
        at com.ugleh.redstoneproximitysensor.utils.Glow.<init>(Glow.java:10) ~[?:?]
        at com.ugleh.redstoneproximitysensor.RedstoneProximitySensor.onEnable(RedstoneProximitySensor.java:56) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:425) [spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:339) [spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562) [spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524) [spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423) [spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by Ugleh** [comment]
Updated to 1.13 and issue closed :)
