### ISSUE TITLE
NPE between PandaWire and RPS

### ISSUE THREAD

**Issue by SlimeDog** [Ugleh/RedstoneProximitySensor#6]
Spigot 1.13.1
RPS 2.3.8
PandaWire 1.0.7

Repeated console/log spam:
```
[07:54:07] [Server thread/ERROR]: Could not pass event BlockRedstoneEvent to RedstoneProximitySensor v2.3.8
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        at net.md_5.PandaRedstoneWire.calculateCurrentChanges(PandaRedstoneWire.java:146) ~[?:?]
        at net.md_5.PandaRedstoneWire.a(PandaRedstoneWire.java:86) ~[?:?]
        at net.md_5.PandaRedstoneWire.doPhysics(PandaRedstoneWire.java:495) ~[?:?]
        at net.minecraft.server.v1_13_R2.IBlockData.doPhysics(SourceFile:241) ~[spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.World.a(World.java:545) ~[spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.World.a(World.java:508) ~[spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.BlockDiodeAbstract.d(BlockDiodeAbstract.java:172) ~[spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.BlockDiodeAbstract.onPlace(BlockDiodeAbstract.java:154) ~[spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.IBlockData.onPlace(SourceFile:253) ~[spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.Chunk.a(Chunk.java:525) ~[spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.World.setTypeAndData(World.java:318) ~[spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.BlockDiodeAbstract.a(BlockDiodeAbstract.java:39) ~[spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.IBlockData.a(SourceFile:261) ~[spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.WorldServer.b(WorldServer.java:677) ~[spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.TickListServer.a(TickListServer.java:77) [spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.WorldServer.q(WorldServer.java:659) [spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:301) [spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:952) [spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at com.ugleh.redstoneproximitysensor.listeners.SensorListener.BlockRedstoneEvent(SensorListener.java:23) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.1.jar-2018-09-04-1018:git-Spigot-0ede7d0-c88ae6b]
        ... 25 more
```

**Comment by SlimeDog** [comment]
Wow! PandaWire and RPS certainly don't like each other. :(

I disabled (removed) PandaWire, and there are no errors reported by RPS. So this probably an issue with PandaWire. Posted a note there.

**Comment by SlimeDog** [comment]
Fixed by PandaWire. Thanks md_5.
