### ISSUE TITLE
EventException on delete from creative inventory

### ISSUE THREAD

**Issue by SlimeDog** [Ugleh/RedstoneProximitySensor#7]
Spigot 1.14
RPS 2.3.9

RPS works correctly, but in creative mode:
- Give player a RPS
- Remove RPS from inventory, dragging to X

This does not occur with Spigot 1.13.2 final.

```
[07:11:22] [Server thread/ERROR]: Could not pass event InventoryCreativeEvent to RedstoneProximitySensor v2.3.9
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.14.jar-2019-04-27-1757:git-Spigot-0da6fe2-f4f3295]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.jar-2019-04-27-1757:git-Spigot-0da6fe2-f4f3295]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) ~[spigot-1.14.jar-2019-04-27-1757:git-Spigot-0da6fe2-f4f3295]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) ~[spigot-1.14.jar-2019-04-27-1757:git-Spigot-0da6fe2-f4f3295]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2315) ~[spigot-1.14.jar-2019-04-27-1757:git-Spigot-0da6fe2-f4f3295]
        at net.minecraft.server.v1_14_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23) ~[spigot-1.14.jar-2019-04-27-1757:git-Spigot-0da6fe2-f4f3295]
        at net.minecraft.server.v1_14_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9) ~[spigot-1.14.jar-2019-04-27-1757:git-Spigot-0da6fe2-f4f3295]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.jar-2019-04-27-1757:git-Spigot-0da6fe2-f4f3295]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.jar-2019-04-27-1757:git-Spigot-0da6fe2-f4f3295]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.jar-2019-04-27-1757:git-Spigot-0da6fe2-f4f3295]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.jar-2019-04-27-1757:git-Spigot-0da6fe2-f4f3295]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.jar-2019-04-27-1757:git-Spigot-0da6fe2-f4f3295]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:892) [spigot-1.14.jar-2019-04-27-1757:git-Spigot-0da6fe2-f4f3295]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:885) [spigot-1.14.jar-2019-04-27-1757:git-Spigot-0da6fe2-f4f3295]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.jar-2019-04-27-1757:git-Spigot-0da6fe2-f4f3295]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:869) [spigot-1.14.jar-2019-04-27-1757:git-Spigot-0da6fe2-f4f3295]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:802) [spigot-1.14.jar-2019-04-27-1757:git-Spigot-0da6fe2-f4f3295]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getName()Ljava/lang/String;
        at com.ugleh.redstoneproximitysensor.listeners.PlayerListener.InventoryClickEvent(PlayerListener.java:188) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:311) ~[spigot-1.14.jar-2019-04-27-1757:git-Spigot-0da6fe2-f4f3295]
        ... 17 more
```

**Comment by Ugleh** [comment]
Sorry about not getting back to this. I wasn't getting any emails about this. Problem resolved in last release.
